run:
  timeout: 3m
  allow-parallel-runners: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
linters:
  enable:
    - revive
    - copyloopvar
    - decorder
    - errname
    - errorlint
    - exhaustive
    - gofmt
    - goimports
    - gosec
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nilerr
    - noctx
    - paralleltest
    - prealloc
    - reassign
    - tenv
    - typecheck
    - unconvert
    - usestdlibvars
    - whitespace
linters-settings:
  misspell:
    locale: US
